import DataViewLayoutOptions from 'primevue/dataviewlayoutoptions';
import ConfirmationService from 'primevue/confirmationservice';
import 'primevue/resources/themes/lara-light-green/theme.css';
import OrganizationChart from 'primevue/organizationchart';
import TriStateCheckbox from 'primevue/tristatecheckbox';
import 'primevue/resources/themes/saga-blue/theme.css';
import AnimateOnScroll from 'primevue/animateonscroll';
import DeferredContent from 'primevue/deferredcontent';
import InputGroupAddon from 'primevue/inputgroupaddon';
import ProgressSpinner from 'primevue/progressspinner';
import VirtualScroller from 'primevue/virtualscroller';
import BadgeDirective from 'primevue/badgedirective';
import CascadeSelect from 'primevue/cascadeselect';
import ConfirmDialog from 'primevue/confirmdialog';
import DialogService from 'primevue/dialogservice';
import DynamicDialog from 'primevue/dynamicdialog';
import InlineMessage from 'primevue/inlinemessage';
import SplitterPanel from 'primevue/splitterpanel';
import AccordionTab from 'primevue/accordiontab';
import AutoComplete from 'primevue/autocomplete';
import ConfirmPopup from 'primevue/confirmpopup';
import OverlayPanel from 'primevue/overlaypanel';
import SelectButton from 'primevue/selectbutton';
import ToastService from 'primevue/toastservice';
import ToggleButton from 'primevue/togglebutton';
import AvatarGroup from 'primevue/avatargroup';
import ColorPicker from 'primevue/colorpicker';
import ColumnGroup from 'primevue/columngroup';
import ContextMenu from 'primevue/contextmenu';
import InputNumber from 'primevue/inputnumber';
import InputSwitch from 'primevue/inputswitch';
import MultiSelect from 'primevue/multiselect';
import ProgressBar from 'primevue/progressbar';
import RadioButton from 'primevue/radiobutton';
import ScrollPanel from 'primevue/scrollpanel';
import SplitButton from 'primevue/splitbutton';
import Breadcrumb from 'primevue/breadcrumb';
import FileUpload from 'primevue/fileupload';
import InputGroup from 'primevue/inputgroup';
import StyleClass from 'primevue/styleclass';
import TieredMenu from 'primevue/tieredmenu';
import TreeSelect from 'primevue/treeselect';
import Accordion from 'primevue/accordion';
import DataTable from 'primevue/datatable';
import FocusTrap from 'primevue/focustrap';
import InputMask from 'primevue/inputmask';
import InputText from 'primevue/inputtext';
import OrderList from 'primevue/orderlist';
import Paginator from 'primevue/paginator';
import PanelMenu from 'primevue/panelmenu';
import ScrollTop from 'primevue/scrolltop';
import SpeedDial from 'primevue/speeddial';
import TreeTable from 'primevue/treetable';
import Calendar from 'primevue/calendar';
import Carousel from 'primevue/carousel';
import Checkbox from 'primevue/checkbox';
import Dropdown from 'primevue/dropdown';
import Fieldset from 'primevue/fieldset';
import Galleria from 'primevue/galleria';
import MegaMenu from 'primevue/megamenu';
import Password from 'primevue/password';
import PickList from 'primevue/picklist';
import Skeleton from 'primevue/skeleton';
import Splitter from 'primevue/splitter';
import TabPanel from 'primevue/tabpanel';
import Terminal from 'primevue/terminal';
import Textarea from 'primevue/textarea';
import Timeline from 'primevue/timeline';
import BlockUI from 'primevue/blockui';
import Divider from 'primevue/divider';
import Inplace from 'primevue/inplace';
import Listbox from 'primevue/listbox';
import Menubar from 'primevue/menubar';
import Message from 'primevue/message';
import Sidebar from 'primevue/sidebar';
import TabMenu from 'primevue/tabmenu';
import TabView from 'primevue/tabview';
import Toolbar from 'primevue/toolbar';
import Tooltip from 'primevue/tooltip';
import PrimeVue from 'primevue/config';
import Avatar from 'primevue/avatar';
import Button from 'primevue/button';
import Column from 'primevue/column';
import Dialog from 'primevue/dialog';
import Rating from 'primevue/rating';
import Ripple from 'primevue/ripple';
import Slider from 'primevue/slider';
import 'primeicons/primeicons.css';
import Badge from 'primevue/badge';
import Chips from 'primevue/chips';
import Image from 'primevue/image';
import Panel from 'primevue/panel';
import Steps from 'primevue/steps';
import Toast from 'primevue/toast';
import 'primeflex/primeflex.css';
import Card from 'primevue/card';
import Chip from 'primevue/chip';
import Dock from 'primevue/dock';
import Knob from 'primevue/knob';
import Menu from 'primevue/menu';
import Tree from 'primevue/tree';
import Row from 'primevue/row';
import Tag from 'primevue/tag';

const primeConfig = { ripple: true };

export const registerPrimeVue = (app: any) => {
	app.use(PrimeVue, primeConfig);
	app.use(ConfirmationService);
	app.use(ToastService);
	app.use(DialogService);

	app.directive('tooltip', Tooltip);
	app.directive('badge', BadgeDirective);
	app.directive('ripple', Ripple);
	app.directive('styleclass', StyleClass);
	app.directive('focustrap', FocusTrap);
	app.directive('animateonscroll', AnimateOnScroll);

	app.component('Accordion', Accordion);
	app.component('AccordionTab', AccordionTab);
	app.component('AutoComplete', AutoComplete);
	app.component('Avatar', Avatar);
	app.component('AvatarGroup', AvatarGroup);
	app.component('Badge', Badge);
	app.component('BlockUI', BlockUI);
	app.component('Breadcrumb', Breadcrumb);
	app.component('Button', Button);
	app.component('Calendar', Calendar);
	app.component('Card', Card);
	app.component('Carousel', Carousel);
	app.component('CascadeSelect', CascadeSelect);
	app.component('Checkbox', Checkbox);
	app.component('Chip', Chip);
	app.component('Chips', Chips);
	app.component('ColorPicker', ColorPicker);
	app.component('Column', Column);
	app.component('ColumnGroup', ColumnGroup);
	app.component('ConfirmDialog', ConfirmDialog);
	app.component('ConfirmPopup', ConfirmPopup);
	app.component('ContextMenu', ContextMenu);
	app.component('DataTable', DataTable);
	app.component('DataView', DataView);
	app.component('DataViewLayoutOptions', DataViewLayoutOptions);
	app.component('DeferredContent', DeferredContent);
	app.component('Dialog', Dialog);
	app.component('Divider', Divider);
	app.component('Dock', Dock);
	app.component('Dropdown', Dropdown);
	app.component('DynamicDialog', DynamicDialog);
	app.component('Fieldset', Fieldset);
	app.component('FileUpload', FileUpload);
	app.component('Galleria', Galleria);
	app.component('Image', Image);
	app.component('InlineMessage', InlineMessage);
	app.component('Inplace', Inplace);
	app.component('InputGroup', InputGroup);
	app.component('InputGroupAddon', InputGroupAddon);
	app.component('InputMask', InputMask);
	app.component('InputNumber', InputNumber);
	app.component('InputSwitch', InputSwitch);
	app.component('InputText', InputText);
	app.component('Knob', Knob);
	app.component('Listbox', Listbox);
	app.component('MegaMenu', MegaMenu);
	app.component('Menu', Menu);
	app.component('Menubar', Menubar);
	app.component('Message', Message);
	app.component('MultiSelect', MultiSelect);
	app.component('OrderList', OrderList);
	app.component('OrganizationChart', OrganizationChart);
	app.component('OverlayPanel', OverlayPanel);
	app.component('Paginator', Paginator);
	app.component('Panel', Panel);
	app.component('PanelMenu', PanelMenu);
	app.component('Password', Password);
	app.component('PickList', PickList);
	app.component('ProgressBar', ProgressBar);
	app.component('ProgressSpinner', ProgressSpinner);
	app.component('RadioButton', RadioButton);
	app.component('Rating', Rating);
	app.component('Row', Row);
	app.component('SelectButton', SelectButton);
	app.component('ScrollPanel', ScrollPanel);
	app.component('ScrollTop', ScrollTop);
	app.component('Slider', Slider);
	app.component('Sidebar', Sidebar);
	app.component('Skeleton', Skeleton);
	app.component('SpeedDial', SpeedDial);
	app.component('SplitButton', SplitButton);
	app.component('Splitter', Splitter);
	app.component('SplitterPanel', SplitterPanel);
	app.component('Steps', Steps);
	app.component('TabMenu', TabMenu);
	app.component('TabView', TabView);
	app.component('TabPanel', TabPanel);
	app.component('Tag', Tag);
	app.component('Textarea', Textarea);
	app.component('Terminal', Terminal);
	app.component('TieredMenu', TieredMenu);
	app.component('Timeline', Timeline);
	app.component('Toast', Toast);
	app.component('Toolbar', Toolbar);
	app.component('ToggleButton', ToggleButton);
	app.component('Tree', Tree);
	app.component('TreeSelect', TreeSelect);
	app.component('TreeTable', TreeTable);
	app.component('TriStateCheckbox', TriStateCheckbox);
	app.component('VirtualScroller', VirtualScroller);
};
